### ISSUE TITLE
Remove callbacks in methods

### ISSUE THREAD

**Issue by mourner** [leaflet-extras/RTree#17]
What is the reason behind adding the callback arguments to purely synchronous methods? It doesn't add any value since all the methods are still sync, but complicates the code.

**Comment by calvinmetcalf** [comment]
the main reasons for adding a callback options were to make it more idiomatic for use in Node and to add hooks for latter latter adding true async to it like if we wanted to add an option to have the rtree put into a worker or indexedDB.  The callbacks are all in public facing functions that are just sugar for calling internal functions, in theory, some of them not so well done which is a problem

e.g. [this isn't too bad](https://github.com/leaflet-extras/RTree/blob/master/src/rtree.js#L426-L441) but [this needs to be improved](https://github.com/leaflet-extras/RTree/blob/master/src/rtree.js#L529-L556)

**Comment by mourner** [comment]
I think that it's not a good idea for the API. First, idiomatic Node never accepts callbacks in methods that are not in fact asynchronous, e.g. `readFileSync` etc., so adding callbacks in synchronous code in fact contradicts Node principles. Second, from architectural point of view it's better to separate sync and async APIs and corresponding implementations. So when you actually implement async-working RTree, I'd rather see it as an extension with additional methods or a wrapper around the basic sync library than tightly coupled into the main code, because not everyone needs core async, and some people will want to implement their own.

**Comment by mourner** [comment]
And as a general remark, simpler = better. Adding complexity for _possible_ future enhancements is overengineering.

**Comment by calvinmetcalf** [comment]
At the moment [this version](https://github.com/leaflet-extras/RTree/blob/multifile/src/rtree.js#L417-L442) doesn't add too much complexity (and is certainly simpler than the [original version](https://github.com/imbcmdth/RTree/blob/master/src/rtree.js#L559-L583)) we can come back to this after I figure out #15 which as far as I can tell has been in the library since the origional but just wasn't pickup up because the tests were all [non-deterministic](https://github.com/imbcmdth/RTree/blob/master/tests/unit.html#L12-L31)
